version: "3.8"
services:
  backend:
    image: "chrvillaruel/springboot-react-fullstack:5.4.2021.10.6.1"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev